import type { Product } from "@/types";

export const PRODUCTS: Product[] = [
  // 1. 기존 원두들
  {
    id: "p-1001",
    title_ko: "시그니처 원두",
    title_ja: "シグネチャーコーヒー豆",
    description_ko: "밸런스 좋은 데일리 블렌드",
    description_ja: "バランスの良いデイリーブレンド",
    price: 25000,
    category: "beans",
    imageUrl: "/beans.jpg",
    isActive: true,
    createdAt: 1730000000000,
  },
  {
    id: "p-1002",
    title_ko: "글라스 컵",
    title_ja: "グラスカップ",
    description_ko: "심플한 로고 컵",
    description_ja: "シンプルなロゴカップ",
    price: 18000,
    category: "goods",
    imageUrl: "/glass.jpg",
    isActive: true,
    createdAt: 1730000100000,
  },
  {
    id: "p-1003",
    title_ko: "오리지널 원두",
    title_ja: "オリジナル豆",
    description_ko: "견과류 향미",
    description_ja: "ナッツのフレーバー",
    price: 18500,
    category: "beans",
    imageUrl: "/beans2.jpg",
    isActive: true,
    createdAt: 1730000200000,
  },

  // 2. 싱글 오리진 / 스페셜티
  {
    id: "p-1004",
    title_ko: "에티오피아 예가체프",
    title_ja: "エチオピア・イルガチェフェ",
    description_ko: "꽃향과 베리류 산미가 있는 라이트 로스트",
    description_ja: "フローラルな香りとベリー系の酸味を楽しめるライトロースト",
    price: 27000,
    category: "beans",
    imageUrl: "/beans-ethiopia.jpg",
    isActive: true,
    createdAt: 1730000300000,
  },
  {
    id: "p-1005",
    title_ko: "콜롬비아 수프리모",
    title_ja: "コロンビア・スプレモ",
    description_ko: "초콜릿과 카라멜 향, 누구나 즐기는 클래식 커피",
    description_ja: "チョコとキャラメルの香りで飲みやすいクラシックなコーヒー",
    price: 26000,
    category: "beans",
    imageUrl: "/beans-colombia.jpg",
    isActive: true,
    createdAt: 1730000400000,
  },
  {
    id: "p-1006",
    title_ko: "디카페인 하우스블렌드",
    title_ja: "デカフェ・ハウスブレンド",
    description_ko: "카페인 줄이고도 풍미는 그대로, 밤에도 부담 없이",
    description_ja: "カフェインを控えたい方に。香りとコクはそのまま",
    price: 24000,
    category: "beans",
    imageUrl: "/beans-decaf.jpg",
    isActive: true,
    createdAt: 1730000500000,
  },

  // 3. 드립백 / 홈브루용
  {
    id: "p-1007",
    title_ko: "데일리 드립백 (5개입)",
    title_ja: "デイリードリップバッグ（5袋）",
    description_ko: "사무실·기숙사 어디서나 간편하게 즐기는 드립커피",
    description_ja: "どこでも手軽に飲めるドリップコーヒーセット",
    price: 9800,
    category: "drip",
    imageUrl: "/dripbag.jpg",
    isActive: true,
    createdAt: 1730000600000,
  },
  {
    id: "p-1008",
    title_ko: "콜드브루 파우치 (4팩)",
    title_ja: "コールドブリュー用パック（4パック）",
    description_ko: "물만 부어 냉장고에 넣어두면 다음날 완성",
    description_ja: "水に浸して冷蔵庫に入れるだけの簡単コールドブリュー",
    price: 15000,
    category: "drip",
    imageUrl: "/coldbrew-pack.jpg",
    isActive: true,
    createdAt: 1730000700000,
  },

  // 4. 텀블러 / 머그 / 굿즈
  {
    id: "p-1009",
    title_ko: "로고 머그 350ml",
    title_ja: "ロゴマグ 350ml",
    description_ko: "매트한 질감의 데일리 머그",
    description_ja: "マットな質感のデイリーマグ",
    price: 21000,
    category: "goods",
    imageUrl: "/mug.jpg",
    isActive: true,
    createdAt: 1730000800000,
  },
  {
    id: "p-1010",
    title_ko: "더블월 텀블러 500ml",
    title_ja: "ダブルウォールタンブラー 500ml",
    description_ko: "아이스 라떼도 결로 없이 시원하게",
    description_ja: "アイスラテも結露しにくく、冷たさキープ",
    price: 29000,
    category: "tumbler",
    imageUrl: "/tumbler.jpg",
    isActive: true,
    createdAt: 1730000900000,
  },
  {
    id: "p-1011",
    title_ko: "시그니처 코스터 (2개 세트)",
    title_ja: "シグネチャーコースター（2枚セット）",
    description_ko: "우드 질감으로 집에서 카페 감성",
    description_ja: "木目調でおうちカフェを演出",
    price: 12000,
    category: "goods",
    imageUrl: "/coaster.jpg",
    isActive: true,
    createdAt: 1730001000000,
  },
  {
    id: "p-1012",
    title_ko: "브랜드 토트백",
    title_ja: "ブランドトートバッグ",
    description_ko: "원두 사러 갈 때 쓰기 좋은 코튼백",
    description_ja: "コーヒー豆を買いに行く時にちょうどいいコットンバッグ",
    price: 22000,
    category: "goods",
    imageUrl: "/totebag.jpg",
    isActive: true,
    createdAt: 1730001100000,
  },

  // 5. 시즌 한정
  {
    id: "p-1013",
    title_ko: "가을 시나몬 시럽",
    title_ja: "オータム・シナモンシロップ",
    description_ko: "라떼에 한 펌프만 넣어도 카페 향 가득",
    description_ja: "ラテに1プッシュで季節の香りに",
    price: 13000,
    category: "seasonal",
    imageUrl: "/syrup-cinnamon.jpg",
    isActive: true,
    createdAt: 1730001200000,
  },
  {
    id: "p-1014",
    title_ko: "바닐라 빈 시럽",
    title_ja: "バニラビーンズシロップ",
    description_ko: "홈카페 기본템, 콜드브루랑 찰떡",
    description_ja: "おうちカフェの定番。コールドブリューとも相性◎",
    price: 13500,
    category: "seasonal",
    imageUrl: "/syrup-vanilla.jpg",
    isActive: true,
    createdAt: 1730001300000,
  },

  // 6. 캡슐 / 머신용
  {
    id: "p-1015",
    title_ko: "에스프레소 캡슐 다크 (10개입)",
    title_ja: "エスプレッソカプセル・ダーク（10個入り）",
    description_ko: "초콜릿과 로스티 풍미가 강한 캡슐",
    description_ja: "チョコとロースト感がしっかりしたカプセルコーヒー",
    price: 11000,
    category: "capsule",
    imageUrl: "/capsule-dark.jpg",
    isActive: true,
    createdAt: 1730001400000,
  },
  {
    id: "p-1016",
    title_ko: "에스프레소 캡슐 디카페인 (10개입)",
    title_ja: "エスプレッソカプセル・デカフェ（10個入り）",
    description_ko: "늦은 밤에도 부담 없는 캡슐",
    description_ja: "夜でも気軽に楽しめるデカフェカプセル",
    price: 11500,
    category: "capsule",
    imageUrl: "/capsule-decaf.jpg",
    isActive: true,
    createdAt: 1730001500000,
  },

  // 7. 기프트 세트
  {
    id: "p-1017",
    title_ko: "커피 러버 기프트 박스",
    title_ja: "コーヒーラバーズ・ギフトボックス",
    description_ko: "원두 200g + 드립백 3개 + 코스터 1세트",
    description_ja: "コーヒー豆200gとドリップバッグ3つ、コースターのセット",
    price: 39000,
    category: "gift",
    imageUrl: "/giftbox.jpg",
    isActive: true,
    createdAt: 1730001600000,
  },
  {
    id: "p-1018",
    title_ko: "브루잉 스타터 세트",
    title_ja: "ブリューイングスターターセット",
    description_ko: "핸드드립 시작하려는 분들을 위한 기본 세트",
    description_ja: "ハンドドリップを始めたい方向けのスターター",
    price: 42000,
    category: "gift",
    imageUrl: "/brewing-starter.jpg",
    isActive: true,
    createdAt: 1730001700000,
  },

  // 8. 굿즈 추가
  {
    id: "p-1019",
    title_ko: "서머 투명 텀블러 450ml",
    title_ja: "サマークリアタンブラー 450ml",
    description_ko: "아이스 아메리카노 전용으로 딱 맞는 사이즈",
    description_ja: "アイスアメリカーノにぴったりのサイズ感",
    price: 25000,
    category: "tumbler",
    imageUrl: "/tumbler-clear.jpg",
    isActive: true,
    createdAt: 1730001800000,
  },
  {
    id: "p-1020",
    title_ko: "로고 스티커팩",
    title_ja: "ロゴステッカーパック",
    description_ko: "텀블러, 노트북 어디든 붙일 수 있는 방수 스티커",
    description_ja: "タンブラーやPCにも貼れる防水ステッカー",
    price: 7000,
    category: "goods",
    imageUrl: "/stickers.jpg",
    isActive: true,
    createdAt: 1730001900000,
  },
];
